# Generated by Django 4.2.22 on 2025-08-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_items/'),
        ),
    ]
