# Generated by Django 4.2.22 on 2025-08-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_orderitem_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_image',
        ),
    ]
