# Generated by Django 4.2.22 on 2025-09-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]
