# Generated by Django 4.2.22 on 2025-08-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('assigned', 'Assigned to Delivery Partner'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=30),
        ),
    ]
