# Generated by Django 4.2.22 on 2025-08-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_order_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='placed_at',
        ),
    ]
