# Generated by Django 4.2.22 on 2025-08-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_order_placed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_at',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
