# Generated by Django 4.2.22 on 2025-08-29 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_order_order_date_alter_order_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
